version: '3.9'

services:
  mongodb:
    image: bitnami/mongodb:latest
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=localhost
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_KEY=kuncirahasia123
      - MONGODB_ROOT_PASSWORD=root123
      - MONGODB_REPLICA_SET_NAME=rs0
    volumes:
      - mongo_data_bitnami:/bitnami/mongodb

volumes:
  mongo_data_bitnami:
